import json

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "md-title",
   "metadata": {},
   "source": [
    "# AIMO Progress Prize 3 — TIR Baseline Pipeline\n",
    "\n",
    "**Approach**: Tool-Integrated Reasoning (TIR) + Self-Correction + Majority Voting\n",
    "\n",
    "- Engine: `transformers` + `bitsandbytes` (pre-installed on Kaggle, no internet needed)\n",
    "- Inference: generate `NUM_SAMPLES` independent samples → majority vote\n",
    "- TIR: LLM writes Python → sandbox executes → output fed back → self-correct"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 1: Imports & Environment Detection\n",
    "# ============================================================\n",
    "import os\n",
    "import re\n",
    "import sys\n",
    "import time\n",
    "import tempfile\n",
    "import subprocess\n",
    "from pathlib import Path\n",
    "from collections import Counter\n",
    "from typing import List, Optional\n",
    "\n",
    "import torch\n",
    "import pandas as pd\n",
    "\n",
    "IS_KAGGLE = Path('/kaggle/input').exists()\n",
    "print(f\"Environment : {'Kaggle' if IS_KAGGLE else 'Local (mock mode)'}\")\n",
    "print(f\"Python      : {sys.version.split()[0]}\")\n",
    "print(f\"PyTorch     : {torch.__version__}\")\n",
    "print(f\"CUDA        : {torch.cuda.is_available()} \"\n",
    "      f\"({torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A'})\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-config",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 2: Configuration\n",
    "# ============================================================\n",
    "\n",
    "# --- Model (Kaggle Dataset slug) ---\n",
    "# Add the dataset via kernel-metadata.json dataset_sources.\n",
    "# Recommended: deepseek-ai/deepseek-r1-distill-qwen-7b (7B, fits P100 16 GB in INT4)\n",
    "MODEL_DATASET   = 'deepseek-r1-distill-qwen-7b'          # dataset slug\n",
    "MODEL_PATH      = f'/kaggle/input/{MODEL_DATASET}'        # full path on Kaggle\n",
    "LOAD_IN_4BIT    = True    # INT4 via bitsandbytes; set False for FP16 (needs >14 GB VRAM for 7B)\n",
    "\n",
    "# --- Context ---\n",
    "MAX_MODEL_LEN   = 8192    # hard cap for prompt+generation (P100 memory budget)\n",
    "\n",
    "# --- Sampling ---\n",
    "NUM_SAMPLES     = 8 if IS_KAGGLE else 4    # maj@N\n",
    "TEMPERATURE     = 0.6\n",
    "TOP_P           = 0.95\n",
    "MAX_NEW_TOKENS  = 4096    # per sample (keep lower to fit memory + 9 h time budget)\n",
    "\n",
    "# --- TIR self-correction ---\n",
    "MAX_TIR_ROUNDS  = 3\n",
    "CODE_TIMEOUT    = 30      # seconds per code block\n",
    "\n",
    "# --- I/O ---\n",
    "if IS_KAGGLE:\n",
    "    TEST_CSV = '/kaggle/input/ai-mathematical-olympiad-progress-prize-3/test.csv'\n",
    "else:\n",
    "    TEST_CSV = 'dummy_test.csv'\n",
    "OUTPUT_CSV = 'submission.csv'\n",
    "\n",
    "print('Configuration:')\n",
    "for k, v in {\n",
    "    'MODEL_PATH': MODEL_PATH, 'LOAD_IN_4BIT': LOAD_IN_4BIT,\n",
    "    'NUM_SAMPLES': NUM_SAMPLES, 'MAX_NEW_TOKENS': MAX_NEW_TOKENS,\n",
    "    'MAX_TIR_ROUNDS': MAX_TIR_ROUNDS, 'CODE_TIMEOUT': CODE_TIMEOUT,\n",
    "}.items():\n",
    "    print(f'  {k:20s}: {v}')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-sandbox",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 3: Python Sandbox\n",
    "# ============================================================\n",
    "\n",
    "def execute_python(code: str, timeout: int = CODE_TIMEOUT) -> str:\n",
    "    \"\"\"Run code in isolated subprocess; return stdout+stderr (max 2000 chars).\"\"\"\n",
    "    with tempfile.NamedTemporaryFile(\n",
    "        mode='w', suffix='.py', delete=False, encoding='utf-8'\n",
    "    ) as f:\n",
    "        f.write(code)\n",
    "        tmp_path = f.name\n",
    "    try:\n",
    "        proc = subprocess.run(\n",
    "            [sys.executable, tmp_path],\n",
    "            capture_output=True, text=True, timeout=timeout,\n",
    "        )\n",
    "        output = proc.stdout + proc.stderr or '(no output)'\n",
    "    except subprocess.TimeoutExpired:\n",
    "        output = f'TimeoutError: exceeded {timeout}s'\n",
    "    except Exception as exc:\n",
    "        output = f'ExecutionError: {exc}'\n",
    "    finally:\n",
    "        try:\n",
    "            os.unlink(tmp_path)\n",
    "        except OSError:\n",
    "            pass\n",
    "    if len(output) > 2000:\n",
    "        output = output[:1500] + '\\n...[truncated]...\\n' + output[-500:]\n",
    "    return output.rstrip()\n",
    "\n",
    "\n",
    "_test = execute_python('print(sum(range(1, 101)))')\n",
    "assert _test.strip() == '5050', f'Sandbox failed: {_test!r}'\n",
    "print(f'Sandbox OK -> {_test}')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-prompts",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 4: Prompt Templates & Regex Helpers\n",
    "# ============================================================\n",
    "\n",
    "SYSTEM_PROMPT = (\n",
    "    'You are an expert mathematician solving competition math problems.\\n'\n",
    "    'Reason step by step. You may write Python code to assist with calculations.\\n'\n",
    "    '\\n'\n",
    "    'Wrap Python code in triple backticks:\\n'\n",
    "    '```python\\n'\n",
    "    '# your code here\\n'\n",
    "    '```\\n'\n",
    "    'The code output will be shown to you. Use code for arithmetic, modular arithmetic,\\n'\n",
    "    'combinatorics, exhaustive search, or verification.\\n'\n",
    "    '\\n'\n",
    "    'After reasoning, state your final answer EXACTLY as:\\n'\n",
    "    'The answer is \\\\boxed{<integer>}'\n",
    ")\n",
    "\n",
    "\n",
    "def build_initial_prompt(problem: str) -> str:\n",
    "    return f'{SYSTEM_PROMPT}\\n\\nProblem: {problem}\\n\\nSolution:'\n",
    "\n",
    "\n",
    "_CODE_RE  = re.compile(r'```python\\s*(.*?)```', re.DOTALL)\n",
    "_BOXED_RE = re.compile(r'\\\\boxed\\{([^}]+)\\}')\n",
    "\n",
    "\n",
    "def extract_code_blocks(text: str) -> List[str]:\n",
    "    return [b.strip() for b in _CODE_RE.findall(text)]\n",
    "\n",
    "\n",
    "def extract_final_answer(text: str) -> Optional[str]:\n",
    "    matches = _BOXED_RE.findall(text)\n",
    "    return matches[-1].strip() if matches else None\n",
    "\n",
    "\n",
    "assert extract_final_answer('The answer is \\\\boxed{42}') == '42'\n",
    "assert extract_code_blocks('```python\\nprint(1)\\n```') == ['print(1)']\n",
    "print('Prompt helpers OK')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-model",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 5: Model Loading\n",
    "#   Kaggle : transformers + bitsandbytes (pre-installed, no internet)\n",
    "#   Local  : MockLLM\n",
    "# ============================================================\n",
    "\n",
    "# --- Shared output classes (same interface on both paths) ---\n",
    "class _CompletionOutput:\n",
    "    def __init__(self, text: str): self.text = text\n",
    "\n",
    "class _RequestOutput:\n",
    "    def __init__(self, texts: List[str]):\n",
    "        self.outputs = [_CompletionOutput(t) for t in texts]\n",
    "\n",
    "class SamplingParams:\n",
    "    def __init__(self, temperature=0.6, top_p=0.95, max_tokens=4096, n=1):\n",
    "        self.temperature = temperature\n",
    "        self.top_p = top_p\n",
    "        self.max_tokens = max_tokens\n",
    "        self.n = n\n",
    "\n",
    "\n",
    "if IS_KAGGLE:\n",
    "    # ---- Real model via HuggingFace transformers ----\n",
    "    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig\n",
    "\n",
    "    if not Path(MODEL_PATH).exists():\n",
    "        raise FileNotFoundError(\n",
    "            f'Model not found: {MODEL_PATH}\\n'\n",
    "            f'Add dataset \"{MODEL_DATASET}\" to kernel-metadata.json dataset_sources.'\n",
    "        )\n",
    "\n",
    "    print(f'Loading tokenizer from {MODEL_PATH} ...')\n",
    "    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)\n",
    "    if tokenizer.pad_token is None:\n",
    "        tokenizer.pad_token = tokenizer.eos_token\n",
    "\n",
    "    print(f'Loading model (load_in_4bit={LOAD_IN_4BIT}) ...')\n",
    "    model_kwargs = dict(device_map='auto', trust_remote_code=True)\n",
    "    if LOAD_IN_4BIT:\n",
    "        model_kwargs['quantization_config'] = BitsAndBytesConfig(\n",
    "            load_in_4bit=True,\n",
    "            bnb_4bit_compute_dtype=torch.bfloat16,\n",
    "            bnb_4bit_use_double_quant=True,\n",
    "            bnb_4bit_quant_type='nf4',\n",
    "        )\n",
    "    else:\n",
    "        model_kwargs['torch_dtype'] = torch.float16\n",
    "\n",
    "    hf_model = AutoModelForCausalLM.from_pretrained(MODEL_PATH, **model_kwargs)\n",
    "    hf_model.eval()\n",
    "    print('Model loaded.')\n",
    "    print(f'Device map: {hf_model.hf_device_map}')\n",
    "\n",
    "    class TransformersLLM:\n",
    "        \"\"\"Thin wrapper around hf_model with the same .generate() interface used below.\"\"\"\n",
    "\n",
    "        def generate(self, prompts: List[str], sampling_params: SamplingParams) -> List[_RequestOutput]:\n",
    "            results = []\n",
    "            for prompt in prompts:\n",
    "                enc = tokenizer(\n",
    "                    prompt, return_tensors='pt', truncation=True,\n",
    "                    max_length=MAX_MODEL_LEN - sampling_params.max_tokens,\n",
    "                ).to(hf_model.device)\n",
    "\n",
    "                with torch.no_grad():\n",
    "                    out_ids = hf_model.generate(\n",
    "                        **enc,\n",
    "                        max_new_tokens=sampling_params.max_tokens,\n",
    "                        do_sample=(sampling_params.temperature > 0),\n",
    "                        temperature=max(sampling_params.temperature, 1e-6),\n",
    "                        top_p=sampling_params.top_p,\n",
    "                        num_return_sequences=sampling_params.n,\n",
    "                        pad_token_id=tokenizer.eos_token_id,\n",
    "                        eos_token_id=tokenizer.eos_token_id,\n",
    "                    )\n",
    "\n",
    "                input_len = enc.input_ids.shape[1]\n",
    "                texts = [\n",
    "                    tokenizer.decode(ids[input_len:], skip_special_tokens=True)\n",
    "                    for ids in out_ids\n",
    "                ]\n",
    "                results.append(_RequestOutput(texts))\n",
    "            return results\n",
    "\n",
    "    llm = TransformersLLM()\n",
    "\n",
    "else:\n",
    "    # ---- MockLLM for local testing ----\n",
    "    print('Local mode: using MockLLM')\n",
    "\n",
    "    _MOCK_RESPONSES = [\n",
    "        (\n",
    "            'Let me compute.\\n'\n",
    "            '```python\\n'\n",
    "            'print(sum(range(1, 101)))\\n'\n",
    "            '```\\n'\n",
    "            'The answer is \\\\boxed{5050}'\n",
    "        ),\n",
    "        (\n",
    "            'Writing code:\\n'\n",
    "            '```python\\n'\n",
    "            'print(100 * 101 // 2)\\n'\n",
    "            '```'\n",
    "        ),\n",
    "        'Using formula: 5050. The answer is \\\\boxed{5050}',\n",
    "        'The output confirms it. The answer is \\\\boxed{5050}',\n",
    "    ]\n",
    "\n",
    "    class MockLLM:\n",
    "        _cnt = 0\n",
    "        def generate(self, prompts: List[str], sampling_params: SamplingParams) -> List[_RequestOutput]:\n",
    "            results = []\n",
    "            for _ in prompts:\n",
    "                texts = [\n",
    "                    _MOCK_RESPONSES[(MockLLM._cnt + i) % len(_MOCK_RESPONSES)]\n",
    "                    for i in range(sampling_params.n)\n",
    "                ]\n",
    "                MockLLM._cnt += sampling_params.n\n",
    "                results.append(_RequestOutput(texts))\n",
    "            return results\n",
    "\n",
    "    llm = MockLLM()\n",
    "    print('MockLLM ready.')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-tir",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 6: TIR Inference with Self-Correction\n",
    "# ============================================================\n",
    "\n",
    "def _run_tir_continuation(\n",
    "    conversation: str,\n",
    "    llm_instance,\n",
    "    max_rounds: int = MAX_TIR_ROUNDS,\n",
    ") -> str:\n",
    "    \"\"\"Execute code, feed back output, regenerate until \\\\boxed{} appears or rounds exhausted.\"\"\"\n",
    "    sp = SamplingParams(temperature=TEMPERATURE, top_p=TOP_P, max_tokens=MAX_NEW_TOKENS, n=1)\n",
    "    latest = conversation\n",
    "\n",
    "    for _ in range(max_rounds):\n",
    "        blocks = extract_code_blocks(latest)\n",
    "        if not blocks:\n",
    "            break\n",
    "        code_out = execute_python(blocks[-1])\n",
    "        conversation += (\n",
    "            f'\\n\\nExecution output:\\n```\\n{code_out}\\n```\\n\\n'\n",
    "            'Continue your solution:'\n",
    "        )\n",
    "        out = llm_instance.generate([conversation], sp)\n",
    "        latest = out[0].outputs[0].text\n",
    "        conversation += latest\n",
    "        ans = extract_final_answer(latest)\n",
    "        if ans is not None:\n",
    "            return ans\n",
    "\n",
    "    return extract_final_answer(conversation) or ''\n",
    "\n",
    "\n",
    "def tir_batch(\n",
    "    problem: str,\n",
    "    llm_instance,\n",
    "    num_samples: int = NUM_SAMPLES,\n",
    ") -> List[str]:\n",
    "    \"\"\"Generate num_samples TIR solutions; return list of answer strings.\"\"\"\n",
    "    prompt = build_initial_prompt(problem)\n",
    "    sp = SamplingParams(temperature=TEMPERATURE, top_p=TOP_P, max_tokens=MAX_NEW_TOKENS, n=num_samples)\n",
    "    batch = llm_instance.generate([prompt], sp)\n",
    "\n",
    "    answers: List[str] = []\n",
    "    for sample in batch[0].outputs:\n",
    "        text = sample.text\n",
    "        ans = extract_final_answer(text)\n",
    "        if ans is not None:\n",
    "            answers.append(ans)\n",
    "            continue\n",
    "        if extract_code_blocks(text):\n",
    "            ans = _run_tir_continuation(prompt + text, llm_instance)\n",
    "        else:\n",
    "            nudge = prompt + text + '\\n\\nFinal integer answer: \\\\boxed{'\n",
    "            sp1 = SamplingParams(temperature=0.0, top_p=1.0, max_tokens=64, n=1)\n",
    "            cont = llm_instance.generate([nudge], sp1)\n",
    "            raw = '\\\\boxed{' + cont[0].outputs[0].text\n",
    "            ans = extract_final_answer(raw) or ''\n",
    "        answers.append(ans)\n",
    "    return answers\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-voting",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 7: Self-Consistency (Majority Voting)\n",
    "# ============================================================\n",
    "\n",
    "def majority_vote(answers: List[str]) -> str:\n",
    "    valid = [a for a in answers if a.strip()]\n",
    "    return Counter(valid).most_common(1)[0][0] if valid else '0'\n",
    "\n",
    "\n",
    "def solve_problem(problem: str, llm_instance, num_samples: int = NUM_SAMPLES) -> dict:\n",
    "    all_ans = tir_batch(problem, llm_instance, num_samples)\n",
    "    final   = majority_vote(all_ans)\n",
    "    return {\n",
    "        'answer': final,\n",
    "        'all_answers': all_ans,\n",
    "        'vote_distribution': dict(Counter(a for a in all_ans if a)),\n",
    "        'num_valid': sum(1 for a in all_ans if a),\n",
    "    }\n",
    "\n",
    "\n",
    "print('Voting helpers OK')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-pipeline",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 8: Main Pipeline\n",
    "# ============================================================\n",
    "\n",
    "def run_pipeline(\n",
    "    llm_instance,\n",
    "    test_csv: str = TEST_CSV,\n",
    "    output_csv: str = OUTPUT_CSV,\n",
    "    num_samples: int = NUM_SAMPLES,\n",
    ") -> pd.DataFrame:\n",
    "    df = pd.read_csv(test_csv)\n",
    "    assert {'id', 'problem'}.issubset(df.columns), f'Bad columns: {list(df.columns)}'\n",
    "\n",
    "    rows, total, t0 = [], len(df), time.time()\n",
    "\n",
    "    for i, (_, row) in enumerate(df.iterrows()):\n",
    "        print(f\"\\n{'='*60}\\n[{i+1}/{total}] id={row['id']}\")\n",
    "        print(f\"Problem : {str(row['problem'])[:120]}\")\n",
    "\n",
    "        ts = time.time()\n",
    "        res = solve_problem(row['problem'], llm_instance, num_samples)\n",
    "        print(f\"Answer  : {res['answer']}  Votes: {res['vote_distribution']}  \"\n",
    "              f\"Valid: {res['num_valid']}/{num_samples}  Time: {time.time()-ts:.1f}s\")\n",
    "\n",
    "        rows.append({'id': row['id'], 'answer': res['answer']})\n",
    "\n",
    "    sub = pd.DataFrame(rows)\n",
    "    sub['answer'] = pd.to_numeric(sub['answer'], errors='coerce').fillna(0).astype(int)\n",
    "    sub.to_csv(output_csv, index=False)\n",
    "    print(f\"\\nDone: {total} problems in {(time.time()-t0)/60:.1f} min  ->  {output_csv}\")\n",
    "    print(sub.to_string(index=False))\n",
    "    return sub\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-local-test",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 9: Local Dummy Test  (skipped on Kaggle)\n",
    "# ============================================================\n",
    "\n",
    "if not IS_KAGGLE:\n",
    "    print('>>> Local pipeline test <<<')\n",
    "    dummy = [\n",
    "        {'id': 1, 'problem': 'What is the sum of integers from 1 to 100?'},\n",
    "        {'id': 2, 'problem': 'What is 2^10 mod 7?'},\n",
    "        {'id': 3, 'problem': 'How many primes are less than 20?'},\n",
    "    ]\n",
    "    pd.DataFrame(dummy).to_csv(TEST_CSV, index=False)\n",
    "\n",
    "    sub = run_pipeline(llm, test_csv=TEST_CSV, output_csv=OUTPUT_CSV)\n",
    "\n",
    "    res = pd.read_csv(OUTPUT_CSV)\n",
    "    assert list(res.columns) == ['id', 'answer']\n",
    "    assert len(res) == 3\n",
    "    assert pd.api.types.is_integer_dtype(res['answer'])\n",
    "    print('\\n>>> All assertions passed. <<<')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "cell-kaggle-run",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cell 10: Run on Kaggle\n",
    "# ============================================================\n",
    "\n",
    "if IS_KAGGLE:\n",
    "    submission = run_pipeline(llm, test_csv=TEST_CSV, output_csv=OUTPUT_CSV)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open("ai-mathematical-olympiad-progress-prize-3_1.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Notebook written OK")
